In [8]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
A = np.array([ [1, 2, 3] , [4, 5, 6,] ])
print(A)

[[1 2 3]
 [4 5 6]]


<h1>Exersise 1.1</h1>

In [14]:
def mat_prod():
    A = np.array([ [3, -1, 4], [1, 5, -9] ])
    B = np.array([ [2, 4, -5, 6], [-1, 7, 9, 3], [3, 2, -7, -2] ])
    r = np.dot(A,B)
    return r
    

In [15]:
print(np.dot(A,B))


[[ 19  13 -52   7]
 [-30  21 103  39]]


In [16]:
help(np.dot)

Help on built-in function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
 

In [29]:
for i in range(len(A)):
    for j in range(len(B)):
        r = A[i,j] * B[i,j]
print(r)

-81


<h1>Exercise 1.3</h1>

In [17]:
x = np.array([3, -4, 1] )
y = np.array([5, 2, 3] )
print(x + 10)
print(y * 4)
print(x + y)
print(x * y)

[13  6 11]
[20  8 12]
[ 8 -2  4]
[15 -8  3]


<h1>Exercise 1.4</h1>

In [43]:
A.ndim

2

In [44]:
A.shape

(2, 3)

In [45]:
A.size

6

In [20]:
A.dtype

dtype('int32')

<h1>Exercise 1.5</h1>

In [19]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

A = A.astype('float64')

What does x = np.arange(10) do?
- Change the array to [0 1 2 3 4 5 6 7 8 9]

<h1>Exercise 1.6</h1>

In [23]:
x = np.array([3, -4, 1] )
print(x)
x = np.arange(10)
print(x)

[ 3 -4  1]
[0 1 2 3 4 5 6 7 8 9]


In [24]:
print(x[3])

3


In [25]:
print(x[: 4])

[0 1 2 3]


In [26]:
print(x[4 :])

[4 5 6 7 8 9]


In [27]:
print(x[4:8])

[4 5 6 7]


<h1>Exercise 1.7</h1>

In [28]:
x= np.array([[0,1,2,3,4], [5,6,7,8,9]])
print(x[1, 2])
print(x[:,2:])

7
[[2 3 4]
 [7 8 9]]


In [32]:
x= np.array([[0,1,2,3,4],[5,6,7,8,9]])

In [33]:
print(x[1, 2])

7


In [34]:
print(x[:, 2 :])

[[2 3 4]
 [7 8 9]]


In [29]:
from sklearn import datasets
iris = datasets.load_iris()
print(iris.filename)

C:\Users\sm1sm\Anaconda3\lib\site-packages\sklearn\datasets\data\iris.csv


In [36]:
import numpy as np
iris_data = np.genfromtxt('C:\\Users\\sm1sm\\Anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv', delimiter=",", skip_header=1)
print(data)

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

In [34]:
print('mean of {} is {}'.format(iris.feature_names[0], data[:,0].mean()))

mean of sepal length (cm) is 5.843333333333334


<h1>Exercise 2</h1>

In [37]:
print("mean of {} is {}".format(iris.feature_names[2], iris_data[:,0].mean()))

print("mean of {} is {}".format(iris.feature_names[2], iris_data[:,0].std()))

print("mean of {} is {}".format(iris.feature_names[2], iris_data[:,0].var()))

print("mean of {} is {}".format(iris.feature_names[2], iris_data[:,0].max()))

print("mean of {} is {}".format(iris.feature_names[2], iris_data[:,0].min()))

mean of petal length (cm) is 5.843333333333334
mean of petal length (cm) is 0.8253012917851409
mean of petal length (cm) is 0.6811222222222223
mean of petal length (cm) is 7.9
mean of petal length (cm) is 4.3
